export enum TypeOrmErrorCode {
  DATA_TOO_LONG = 'ER_DATA_TOO_LONG',
  DUPLICATE_KEY = 'ER_DUP_ENTRY',
  NULL_NOT_ALLOWED = 'ER_BAD_NULL_ERROR',
  OUT_OF_RANGE = 'ER_WARN_DATA_OUT_OF_RANGE',
  NO_REFERENCED_ROW = 'ER_NO_REFERENCED_ROW_2',
}
